In [351]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\cm\Desktop\DEPI Project\electronics_supplyChain.csv")

In [352]:
df.head()

,Order ID,Order Date,Ship Date,Delivery Date,Product type,SKU,Category,Price,Discount (%),Number of products sold,...,Lead time,Shipping times,Shipping costs,On-Time Delivery,Supplier name,Supplier Reliability Score,Manufacturing costs,Quality Score,Defect rates,Production volumes
0,ORD1000,19/06/2022,23/06/2022,28/06/2022,Smartphones,SKU0000,Premium,1159.56,13.92,406,...,8,5,38.07,Yes,Supplier 5,0.606,477.03,23.11,7.6892,1084
1,ORD1001,30/03/2022,31/03/2022,11/04/2022,Tablets,SKU0001,Premium,750.06,4.16,100,...,24,11,271.81,Yes,Supplier 4,0.752,271.63,84.46,1.5544,348
2,ORD1002,02/02/2023,04/02/2023,14/02/2023,Laptops,SKU0002,Premium,1867.08,14.90,240,...,24,10,327.91,Yes,Supplier 2,0.655,969.25,14.26,8.5742,356
3,ORD1003,03/03/2023,04/03/2023,07/03/2023,Smartwatches,SKU0003,Premium,361.14,9.73,381,...,15,3,203.27,Yes,Supplier 5,0.625,131.04,73.61,2.6390,246
4,ORD1004,25/06/2024,30/06/2024,06/07/2024,Laptops,SKU0004,Premium,2067.20,11.38,365,...,10,6,28.43,Yes,Supplier 3,0.666,1132.55,59.59,4.0412,1109

In [353]:
print("===== Info =====")
df.info()

===== Info =====
<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Order ID                     1500 non-null   str
 1   Order Date                   1500 non-null   str
 2   Ship Date                    1500 non-null   str
 3   Delivery Date                1500 non-null   str
 4   Product type                 1500 non-null   str
 5   SKU                          1500 non-null   str
 6   Category                     1500 non-null   str
 7   Price                        1500 non-null   float64
 8   Discount (%)                 1500 non-null   float64
 9   Number of products sold      1500 non-null   int64
 10  Units Returned               1500 non-null   int64
 11  Return Reason                1460 non-null   str
 12  Revenue generated            1500 non-null   float64
 13  Profit                       1500 non-null   float64
 14  Customer Satisfaction Score  1500 non-null   float64
 15  Customer demographics        1500 non-null   str
 16  Sales Channel                1500 non-null   str
 17  Payment Method               1500 non-null   str
 18  Region                       1500 non-null   str
 19  Stock levels                 1500 non-null   int64
 20  Reorder Point                1500 non-null   int64
 21  Stockout Risk                1500 non-null   str
 22  Lead time                    1500 non-null   int64
 23  Shipping times               1500 non-null   int64
 24  Shipping costs               1500 non-null   float64
 25  On-Time Delivery             1500 non-null   str
 26  Supplier name                1500 non-null   str
 27  Supplier Reliability Score   1500 non-null   float64
 28  Manufacturing costs          1500 non-null   float64
 29  Quality Score                1500 non-null   float64
 30  Defect rates                 1500 non-null   float64
 31  Production volumes           1500 non-null   int64
dtypes: float64(10), int64(7), str(15)
memory usage: 375.1 KB

In [354]:

print("===== Numerical Summary =====")
df.describe()

===== Numerical Summary =====

,Price,Discount (%),Number of products sold,Units Returned,Revenue generated,Profit,Customer Satisfaction Score,Stock levels,Reorder Point,Lead time,Shipping times,Shipping costs,Supplier Reliability Score,Manufacturing costs,Quality Score,Defect rates,Production volumes
count,1500.000000,1500.000000,1500.000000,1500.000000,1.500000e+03,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,514.657507,7.549733,250.110000,18.373333,1.218708e+05,57084.533780,3.280133,153.940667,193.874000,13.488667,6.928667,176.448453,0.653045,221.836420,50.232133,4.976791,596.293333
std,474.288197,4.365707,142.960611,16.441437,1.542102e+05,72587.006805,1.032516,80.769464,139.756381,6.374608,3.731782,220.410392,0.144501,214.716303,28.905509,2.890545,327.418792
min,20.610000,0.010000,10.000000,0.000000,4.836800e+02,267.470000,1.200000,20.000000,3.000000,3.000000,1.000000,0.160000,0.310000,6.570000,0.110000,0.010500,51.000000
25%,172.275000,3.687500,126.000000,5.000000,2.700131e+04,12425.942500,2.400000,85.000000,81.000000,8.000000,4.000000,33.520000,0.550000,71.237500,25.072500,2.372725,301.500000
50%,370.555000,7.660000,246.000000,14.000000,6.584790e+04,30405.660000,3.300000,152.000000,166.000000,14.000000,7.000000,93.815000,0.648000,156.775000,50.175000,4.982300,591.000000
75%,707.325000,11.280000,375.000000,27.000000,1.508212e+05,72484.055000,4.200000,221.000000,279.000000,19.000000,10.000000,243.070000,0.757000,297.610000,76.272500,7.492900,875.250000
max,2499.950000,15.000000,498.000000,73.000000,1.178621e+06,648842.550000,5.000000,299.000000,694.000000,24.000000,13.000000,1589.800000,0.981000,1344.060000,99.900000,9.989500,1199.000000

In [355]:
print("===== Missing Values =====")
print(df.isnull().sum())

===== Missing Values =====
Order ID                        0
Order Date                      0
Ship Date                       0
Delivery Date                   0
Product type                    0
SKU                             0
Category                        0
Price                           0
Discount (%)                    0
Number of products sold         0
Units Returned                  0
Return Reason                  40
Revenue generated               0
Profit                          0
Customer Satisfaction Score     0
Customer demographics           0
Sales Channel                   0
Payment Method                  0
Region                          0
Stock levels                    0
Reorder Point                   0
Stockout Risk                   0
Lead time                       0
Shipping times                  0
Shipping costs                  0
On-Time Delivery                0
Supplier name                   0
Supplier Reliability Score      0
Manufacturing costs             0
Quality Score                   0
Defect rates                    0
Production volumes              0
dtype: int64

In [356]:
print("Duplicates:", df.duplicated().sum())

print("Duplicates Order ID:", df['Order ID'].duplicated().sum())

display(df[df.duplicated()])

df = df.drop_duplicates()

print("After cleaning:", df.duplicated().sum())

Duplicates: 0
Duplicates Order ID: 0

Empty DataFrame
Columns: [Order ID, Order Date, Ship Date, Delivery Date, Product type, SKU, Category, Price, Discount (%), Number of products sold, Units Returned, Return Reason, Revenue generated, Profit, Customer Satisfaction Score, Customer demographics, Sales Channel, Payment Method, Region, Stock levels, Reorder Point, Stockout Risk, Lead time, Shipping times, Shipping costs, On-Time Delivery, Supplier name, Supplier Reliability Score, Manufacturing costs, Quality Score, Defect rates, Production volumes]
Index: []

[0 rows x 32 columns]

After cleaning: 0

In [357]:
# ---------- Dates ----------
Dates = ['Order Date', 'Ship Date', 'Delivery Date']
for date in Dates :
    df[date] = pd.to_datetime(df[date], errors='coerce', dayfirst=True)

print(df[Dates].info())
print(df[Dates].isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order Date     1500 non-null   datetime64[us]
 1   Ship Date      1500 non-null   datetime64[us]
 2   Delivery Date  1500 non-null   datetime64[us]
dtypes: datetime64[us](3)
memory usage: 35.3 KB
None
Order Date       0
Ship Date        0
Delivery Date    0
dtype: int64

In [358]:
# Keep only logically correct dates
df = df[
    (df["Ship Date"] >= df["Order Date"]) &
    (df["Delivery Date"] >= df["Ship Date"])
]

In [359]:
# ---------- Product ----------
df['Product type'] = df['Product type'].str.lower().str.strip()
df['Category'] = df['Category'].str.lower().str.strip()
df['SKU'] = df['SKU'].astype(str).str.strip()

In [360]:
df['Return Reason'] = df['Return Reason'].str.lower().str.strip()

df[df['Return Reason'].isnull()][['Units Returned', 'Return Reason']]

df[df['Units Returned'] == 0][['Units Returned', 'Return Reason']]

df.loc[df['Units Returned'] == 0, 'Return Reason'] = "no return"

print('Missing Values:', df['Return Reason'].isnull().sum())

df[df['Return Reason'] == "no return"]

Missing Values: 0

,Order ID,Order Date,Ship Date,Delivery Date,Product type,SKU,Category,Price,Discount (%),Number of products sold,...,Lead time,Shipping times,Shipping costs,On-Time Delivery,Supplier name,Supplier Reliability Score,Manufacturing costs,Quality Score,Defect rates,Production volumes
2,ORD1002,2023-02-02,2023-02-04,2023-02-14,laptops,SKU0002,premium,1867.08,14.90,240,...,24,10,327.91,Yes,Supplier 2,0.655,969.25,14.26,8.5742,356
49,ORD1049,2022-04-13,2022-04-14,2022-04-22,laptops,SKU0049,mid-range,710.34,1.12,23,...,15,8,79.15,Yes,Supplier 1,0.783,249.84,48.56,5.1440,277
174,ORD1174,2022-08-06,2022-08-11,2022-08-15,tablets,SKU0174,premium,835.14,5.76,23,...,16,4,132.65,Yes,Supplier 4,0.656,340.12,20.57,7.9426,442
379,ORD1379,2024-05-11,2024-05-13,2024-05-17,smartphones,SKU0379,mid-range,241.72,7.42,12,...,19,4,89.93,Yes,Supplier 2,0.850,82.25,68.85,3.1150,729
444,ORD1444,2024-02-26,2024-02-28,2024-03-10,smartphones,SKU0444,mid-range,531.72,5.18,65,...,18,11,20.16,Yes,Supplier 5,0.647,264.86,12.97,8.7028,993
483,ORD1483,2023-04-13,2023-04-15,2023-04-26,smartwatches,SKU0483,mid-range,174.15,5.62,14,...,20,11,409.92,Yes,Supplier 1,0.865,65.75,69.59,3.0415,213
522,ORD1522,2024-11-09,2024-11-13,2024-11-19,smartphones,SKU0522,mid-range,544.39,12.75,131,...,4,6,199.23,No,Supplier 4,0.645,227.03,12.70,8.7298,763
525,ORD1525,2022-02-16,2022-02-19,2022-02-27,laptops,SKU0525,mid-range,902.15,0.09,162,...,20,8,247.54,Yes,Supplier 4,0.826,491.76,57.21,4.2787,879
588,ORD1588,2023-02-04,2023-02-05,2023-02-07,smartphones,SKU0588,mid-range,259.61,13.65,28,...,8,2,20.41,Yes,Supplier 5,0.750,101.50,38.06,6.1936,154
603,ORD1603,2022-08-13,2022-08-15,2022-08-18,smartphones,SKU0603,mid-range,517.27,13.08,237,...,22,3,139.03,Yes,Supplier 1,0.851,204.14,63.36,3.6635,234
682,ORD1682,2022-08-27,2022-08-30,2022-09-07,smartphones,SKU0682,mid-range,511.81,5.39,246,...,22,8,31.02,Yes,Supplier 4,0.701,271.85,26.08,7.3921,642
690,ORD1690,2024-04-06,2024-04-08,2024-04-21,smartphones,SKU0690,premium,1053.67,2.86,15,...,10,13,348.29,No,Supplier 4,0.801,520.55,60.05,3.9953,378
700,ORD1700,2024-09-17,2024-09-18,2024-09-28,smartphones,SKU0700,premium,1098.59,9.72,12,...,24,10,19.36,Yes,Supplier 4,0.875,488.13,74.37,2.5633,864
722,ORD1722,2023-09-12,2023-09-17,2023-09-24,smartwatches,SKU0722,mid-range,177.63,13.23,15,...,7,7,155.64,Yes,Supplier 3,0.723,67.84,33.41,6.6591,230
742,ORD1742,2023-07-03,2023-07-04,2023-07-15,smartphones,SKU0742,mid-range,489.65,8.72,22,...,23,11,14.01,Yes,Supplier 5,0.669,201.81,23.98,7.6023,676
818,ORD1818,2024-01-29,2024-01-30,2024-02-06,tablets,SKU0818,mid-range,299.63,10.10,169,...,9,7,259.12,Yes,Supplier 3,0.830,143.13,58.56,4.1440,349
862,ORD1862,2022-04-14,2022-04-16,2022-04-27,tablets,SKU0862,mid-range,463.97,12.25,10,...,7,11,64.29,No,Supplier 4,0.743,208.20,53.78,4.6224,1048
906,ORD1906,2022-07-20,2022-07-25,2022-07-30,laptops,SKU0906,mid-range,785.20,11.95,47,...,15,5,25.03,Yes,Supplier 4,0.880,245.68,70.43,2.9572,431
983,ORD1983,2023-11-28,2023-11-30,2023-12-13,headphones,SKU0983,mid-range,101.52,3.07,67,...,11,13,58.36,No,Supplier 4,0.727,40.73,34.09,6.5911,1035
1042,ORD2042,2022-02-15,2022-02-16,2022-02-20,tablets,SKU1042,budget,240.03,14.89,37,...,17,4,48.41,Yes,Supplier 5,0.879,78.42,72.00,2.8003,111
1060,ORD2060,2022-07-12,2022-07-14,2022-07-15,smartwatches,SKU1060,mid-range,188.07,13.47,78,...,13,1,23.01,Yes,Supplier 3,0.609,57.09,2.97,9.7029,986
1068,ORD2068,2024-01-21,2024-01-22,2024-02-03,smartphones,SKU1068,budget,188.40,9.70,68,...,9,12,393.12,No,Supplier 5,0.623,98.98,6.67,9.3326,900
1079,ORD2079,2022-07-06,2022-07-08,2022-07-09,smartwatches,SKU1079,budget,64.07,0.16,42,...,12,1,3.19,Yes,Supplier 3,0.749,35.03,41.86,5.8137,915
1146,ORD2146,2023-11-30,2023-12-03,2023-12-10,tablets,SKU1146,premium,695.72,12.45,417,...,15,7,548.21,Yes,Supplier 4,0.880,240.70,70.46,2.9537,759
1155,ORD2155,2023-01-22,2023-01-26,2023-02-01,smartphones,SKU1155,premium,809.32,10.85,19,...,10,6,392.57,Yes,Supplier 5,0.870,372.93,80.22,1.9784,267
1162,ORD2162,2023-07-26,2023-07-29,2023-08-09,headphones,SKU1162,mid-range,113.85,13.89,186,...,13,11,1358.16,Yes,Supplier 4,0.959,55.26,90.66,0.9336,282
1165,ORD2165,2024-11-18,2024-11-21,2024-11-28,laptops,SKU1165,premium,1705.83,6.47,240,...,14,7,95.18,Yes,Supplier 5,0.888,846.10,73.03,2.6971,979
1174,ORD2174,2024-08-02,2024-08-05,2024-08-10,laptops,SKU1174,mid-range,1070.33,7.52,18,...,18,5,57.69,Yes,Supplier 3,0.776,373.10,44.85,5.5151,114
1229,ORD2229,2024-08-13,2024-08-15,2024-08-23,laptops,SKU1229,premium,1652.75,3.57,139,...,15,8,286.21,Yes,Supplier 1,0.660,656.34,16.80,8.3200,435
1232,ORD2232,2023-12-31,2024-01-02,2024-01-05,laptops,SKU1232,budget,395.33,13.41,42,...,6,3,12.41,Yes,Supplier 4,0.945,177.24,87.18,1.2818,777
1239,ORD2239,2024-12-30,2025-01-03,2025-01-07,tablets,SKU1239,premium,835.61,0.17,10,...,5,4,124.81,Yes,Supplier 2,0.542,284.93,7.27,9.2732,1195
1255,ORD2255,2023-05-03,2023-05-05,2023-05-16,headphones,SKU1255,premium,383.11,7.64,69,...,7,11,30.89,No,Supplier 5,0.718,199.91,29.58,7.0422,550
1265,ORD2265,2023-03-06,2023-03-11,2023-03-15,headphones,SKU1265,budget,76.61,11.06,20,...,23,4,93.82,Yes,Supplier 2,0.950,35.55,94.80,0.5199,364
1279,ORD2279,2023-09-30,2023-10-05,2023-10-12,smartwatches,SKU1279,budget,82.20,3.06,41,...,12,7,125.93,Yes,Supplier 1,0.905,26.53,77.54,2.2456,973
1305,ORD2305,2022-07-03,2022-07-06,2022-07-19,tablets,SKU1305,mid-range,411.99,0.74,62,...,3,13,379.27,No,Supplier 1,0.650,147.18,13.19,8.6806,95
1312,ORD2312,2022-07-19,2022-07-22,2022-08-04,laptops,SKU1312,budget,356.69,3.12,32,...,9,13,300.20,No,Supplier 1,0.697,108.62,26.97,7.3032,958
1363,ORD2363,2024-05-20,2024-05-22,2024-06-02,laptops,SKU1363,mid-range,882.86,7.02,126,...,18,11,74.64,Yes,Supplier 1,0.603,444.28,0.97,9.9030,891
1398,ORD2398,2024-08-27,2024-08-30,2024-09-02,headphones,SKU1398,premium,224.08,13.31,81,...,12,3,60.62,Yes,Supplier 5,0.707,102.60,27.84,7.2163,427
1461,ORD2461,2023-06-27,2023-07-01,2023-07-14,tablets,SKU1461,budget,193.61,14.76,13,...,19,13,854.97,Yes,Supplier 3,0.978,67.24,96.69,0.3311,1148
1466,ORD2466,2024-07-16,2024-07-18,2024-07-19,smartwatches,SKU1466,premium,502.42,8.21,83,...,6,1,20.88,Yes,Supplier 5,0.597,266.43,1.74,9.8265,1071

In [361]:
# ---------- Customer ----------
cols = ['Customer demographics', 'Sales Channel', 'Payment Method', 'Region']
for col in cols:
    df[col] = df[col].str.lower().str.strip() 
    
df['Customer demographics'].value_counts()
    
df['Customer demographics'] = (df['Customer demographics'].replace('unknown', np.nan).ffill())

print(df[df['Customer demographics'] == 'unknown'])

df['Customer demographics'].value_counts()

# ---------- Supplier ----------
df['Supplier name'] = df['Supplier name'].str.lower().str.strip()

Empty DataFrame
Columns: [Order ID, Order Date, Ship Date, Delivery Date, Product type, SKU, Category, Price, Discount (%), Number of products sold, Units Returned, Return Reason, Revenue generated, Profit, Customer Satisfaction Score, Customer demographics, Sales Channel, Payment Method, Region, Stock levels, Reorder Point, Stockout Risk, Lead time, Shipping times, Shipping costs, On-Time Delivery, Supplier name, Supplier Reliability Score, Manufacturing costs, Quality Score, Defect rates, Production volumes]
Index: []

[0 rows x 32 columns]

In [362]:
# Remove Invalid Records
df = df[
    (df["Shipping times"] >= 0) &
    (df["Price"] >= 0) &
    (df["Discount (%)"].between(0,100)) &
    (df["Number of products sold"] > 0) &
    (df["Units Returned"] <= df["Number of products sold"])
]

In [363]:
# =====================================
# Final Data Quality Check
# =====================================

print("\n===== Missing Values =====")
print(df.isnull().sum())

print("\n===== Negative Prices =====")
display(df[df["Price"] < 0])

print("\n===== Invalid Returns =====")
display(df[df["Units Returned"] > df["Number of products sold"]])

print("\n===== Orders =====")
print("Unique Order IDs :", df["Order ID"].nunique())
print("Total Rows :", len(df))

print("\n===== Revenue Sample =====")
display(df[
    [
        "Price",
        "Number of products sold",
        "Discount (%)",
        "Revenue generated"
    ]
].head())

===== Missing Values =====
Order ID                       0
Order Date                     0
Ship Date                      0
Delivery Date                  0
Product type                   0
SKU                            0
Category                       0
Price                          0
Discount (%)                   0
Number of products sold        0
Units Returned                 0
Return Reason                  0
Revenue generated              0
Profit                         0
Customer Satisfaction Score    0
Customer demographics          0
Sales Channel                  0
Payment Method                 0
Region                         0
Stock levels                   0
Reorder Point                  0
Stockout Risk                  0
Lead time                      0
Shipping times                 0
Shipping costs                 0
On-Time Delivery               0
Supplier name                  0
Supplier Reliability Score     0
Manufacturing costs            0
Quality Score                  0
Defect rates                   0
Production volumes             0
dtype: int64

===== Negative Prices =====

Empty DataFrame
Columns: [Order ID, Order Date, Ship Date, Delivery Date, Product type, SKU, Category, Price, Discount (%), Number of products sold, Units Returned, Return Reason, Revenue generated, Profit, Customer Satisfaction Score, Customer demographics, Sales Channel, Payment Method, Region, Stock levels, Reorder Point, Stockout Risk, Lead time, Shipping times, Shipping costs, On-Time Delivery, Supplier name, Supplier Reliability Score, Manufacturing costs, Quality Score, Defect rates, Production volumes]
Index: []

[0 rows x 32 columns]

===== Invalid Returns =====

Empty DataFrame
Columns: [Order ID, Order Date, Ship Date, Delivery Date, Product type, SKU, Category, Price, Discount (%), Number of products sold, Units Returned, Return Reason, Revenue generated, Profit, Customer Satisfaction Score, Customer demographics, Sales Channel, Payment Method, Region, Stock levels, Reorder Point, Stockout Risk, Lead time, Shipping times, Shipping costs, On-Time Delivery, Supplier name, Supplier Reliability Score, Manufacturing costs, Quality Score, Defect rates, Production volumes]
Index: []

[0 rows x 32 columns]

===== Orders =====
Unique Order IDs : 1500
Total Rows : 1500

===== Revenue Sample =====

     Price  Number of products sold  Discount (%)  Revenue generated
0  1159.56                      406         13.92          405248.59
1   750.06                      100          4.16           71885.75
2  1867.08                      240         14.90          381332.42
3   361.14                      381          9.73          124206.41
4  2067.20                      365         11.38          668662.71

In [364]:
# Final Clean Dataset
df_clean = df.copy()

print("Data is ready for analysis.")

Data is ready for analysis.

In [365]:
df_clean.to_csv(r"C:\Users\cm\Desktop\DEPI Project\electronics_supplyChain_clean.csv", index=False)

In [366]:
# ===== 2. Exploratory Data Analysis (EDA) =====

In [367]:
# ===== Domain 1
# ===== Commercial Insights Dashboard | Overview ======

In [368]:
# =====================================
# Q1: Total Revenue
# =====================================

total_revenue = df_clean["Revenue generated"].sum()

print(f"Total Revenue: {total_revenue:,.2f}")

Total Revenue: 182,806,268.33

In [369]:
# =====================================
# Q2: Total Profit
# =====================================

total_profit = df_clean["Profit"].sum()

print(f"Total Profit: {total_profit:,.2f}")

Total Profit: 85,626,800.67

In [370]:
# =====================================
# Q3: Profit Margin
# =====================================

profit_margin = (
    total_profit / total_revenue
) * 100

print(f"Profit Margin: {profit_margin:.2f}%")

Profit Margin: 46.84%

In [371]:
# =====================================
# Q4: Average Discount Percentage
# =====================================

avg_discount = df_clean["Discount (%)"].mean()

print(f"Average Discount: {avg_discount:.2f}%")

Average Discount: 7.55%

In [372]:
# =====================================
# Q5: Revenue & Profit by Quarter
# =====================================

df_clean["Quarter"] = df_clean["Order Date"].dt.to_period("Q")

quarterly_analysis = (
    df_clean
    .groupby("Quarter")[["Revenue generated", "Profit"]]
    .sum()
    .reset_index()
)

quarterly_analysis

   Quarter  Revenue generated      Profit
0   2022Q1        14580525.56  6710772.14
1   2022Q2        16403959.63  7573410.86
2   2022Q3        14237676.70  6911348.93
3   2022Q4        14935634.88  7049973.44
4   2023Q1        14785271.48  7088232.32
5   2023Q2        11679194.83  5362412.86
6   2023Q3        16918444.26  7805106.84
7   2023Q4        17297217.06  7968683.48
8   2024Q1        11581675.95  5531928.25
9   2024Q2        16829300.08  7752014.92
10  2024Q3        14006558.08  6733526.60
11  2024Q4        19550809.82  9139390.03

In [373]:
# =====================================
# Q6: Revenue & Profit by Product
# =====================================

product_analysis = (
    df_clean
    .groupby("Product type")[["Revenue generated", "Profit"]]
    .sum()
    .sort_values(
        by=["Revenue generated", "Profit"],
        ascending=False
    )
)

product_analysis

              Revenue generated       Profit
Product type
laptops             79662632.07  37114017.30
smartphones         40783571.57  19529732.95
tablets             34638181.20  15929751.48
smartwatches        17205532.26   8145736.06
headphones          10516351.23   4907562.88

In [374]:
# =====================================
# Q7: Profit by Sales Channel
# =====================================

sales_channel_profit = (
    df_clean
    .groupby("Sales Channel")[["Profit", "Number of products sold"]]
    .sum()
    .sort_values(by="Profit", ascending=False)
    .reset_index()
)

sales_channel_profit

  Sales Channel       Profit  Number of products sold
0        online  18265991.14                    75250
1     wholesale  17135613.94                    70208
2  retail store  17091983.08                    73170
3           b2b  16882203.33                    80519
4  direct sales  16251009.18                    76018

In [375]:
# =====================================
# Q8: Profit Margin by Region
# =====================================

region_profit_margin = (
    df_clean
    .groupby("Region")
    .agg({
        "Revenue generated":"sum",
        "Profit":"sum"
    })
)

region_profit_margin["Profit Margin (%)"] = (
    region_profit_margin["Profit"] /
    region_profit_margin["Revenue generated"]
) * 100

region_profit_margin = (
    region_profit_margin
    .sort_values(
        by="Profit Margin (%)",
        ascending=False
    )
)

region_profit_margin["Profit Margin (%)"]

Region
south      48.762156
west       47.584795
north      47.011377
east       45.533449
central    45.253460
Name: Profit Margin (%), dtype: float64

In [376]:
# =====================================
# Q9: Discount Distribution (%)
# =====================================

df_clean["Discount Category"] = pd.cut(
    df_clean["Discount (%)"],
    bins=[0, 5, 10, 15],
    labels=["Low", "Medium", "High"],
    include_lowest=True
)

discount_distribution = (
    df_clean["Discount Category"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
    .reset_index()
)

discount_distribution.columns = [
    "Discount Category",
    "Percentage (%)"
]

discount_distribution

  Discount Category  Percentage (%)
0               Low            33.2
1            Medium            31.4
2              High            35.4

In [377]:
# =====================================
# Q10: Revenue & Profit by Gender
# =====================================

gender_analysis = (
    df_clean
    .groupby("Customer demographics")[["Revenue generated","Profit"]]
    .sum()
    .sort_values(
        by="Revenue generated",
        ascending=False
    )
)

gender_analysis

                       Revenue generated       Profit
Customer demographics
male                         63224893.93  29275399.97
female                       61668230.62  29453804.33
non-binary                   57913143.78  26897596.37

In [378]:
# =====================================
# Q11: Revenue & Profit by Discount Category
# =====================================

discount_analysis = (
    df_clean
    .groupby("Discount Category")[["Revenue generated", "Profit"]]
    .sum()
    .reset_index()
)

discount_analysis

  Discount Category  Revenue generated       Profit
0               Low        65675940.40  32376267.65
1            Medium        56632031.91  26545040.58
2              High        60498296.02  26705492.44

In [379]:
# Domain 2
# ===== Customer Experience & Returns =====

In [380]:
# =====================================
# Q1: Average Return Rate
# =====================================

df_clean["Return Rate (%)"] = (
    df_clean["Units Returned"] /
    df_clean["Number of products sold"]
) * 100

avg_return_rate = (
    df_clean["Return Rate (%)"]
    .mean()
)

print(f"Average Return Rate: {avg_return_rate:.2f}%")

Average Return Rate: 7.38%

In [381]:
# =====================================
# Q2: Total Units Returned
# =====================================

total_units_returned = (
    df_clean["Units Returned"]
    .sum()
)

print(f"Total Units Returned: {total_units_returned:,}")

Total Units Returned: 27,560

In [382]:
# =====================================
# Q3: Average Customer Satisfaction Score
# =====================================

avg_satisfaction_score = (
    df_clean["Customer Satisfaction Score"]
    .mean()
)

print(f"Average Customer Satisfaction Score: {avg_satisfaction_score:.2f}")

Average Customer Satisfaction Score: 3.28

In [383]:
# =====================================
# Q4: Total Estimated Return Loss
# =====================================

df_clean["Estimated Return Loss"] = (
    df_clean["Units Returned"] *
    df_clean["Price"]
)

total_return_loss = (
    df_clean["Estimated Return Loss"]
    .sum()
)

print(f"Total Estimated Return Loss: ${total_return_loss:,.2f}")

Total Estimated Return Loss: $14,169,641.75

In [384]:
# =====================================
# Q5: Average Customer Satisfaction Score by Gender
# =====================================

gender_satisfaction = (
    df_clean
    .groupby("Customer demographics")["Customer Satisfaction Score"]
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

gender_satisfaction

  Customer demographics  Customer Satisfaction Score
0                  male                     3.308083
1            non-binary                     3.292484
2                female                     3.237628

In [385]:
# =====================================
# Q6: Return Rate & Return Loss by Region
# =====================================

region_returns = (
    df_clean
    .groupby("Region")
    .agg({
        "Units Returned": "sum",
        "Number of products sold": "sum",
        "Estimated Return Loss": "sum"
    })
)

region_returns["Return Rate (%)"] = (
    region_returns["Units Returned"] /
    region_returns["Number of products sold"]
) * 100

region_returns = (
    region_returns[
        ["Return Rate (%)", "Estimated Return Loss"]
    ]
    .sort_values(
        by="Estimated Return Loss",
        ascending=False
    )
)

region_returns

         Return Rate (%)  Estimated Return Loss
Region
north           6.877025             2908139.53
west            7.447421             2866472.90
east            7.648436             2863131.61
south           7.366804             2767497.59
central         7.424763             2764400.12

In [386]:
# =====================================
# Q7: Return Rate & Units Returned by Sales Channel
# =====================================

sales_channel_returns = (
    df_clean
    .groupby("Sales Channel")
    .agg({
        "Units Returned": "sum",
        "Number of products sold": "sum"
    })
)

sales_channel_returns["Return Rate (%)"] = (
    sales_channel_returns["Units Returned"] /
    sales_channel_returns["Number of products sold"]
) * 100

sales_channel_returns = (
    sales_channel_returns[
        ["Units Returned", "Return Rate (%)"]
    ]
    .sort_values(
        by="Units Returned",
        ascending=False
    )
    .reset_index()
)

sales_channel_returns

  Sales Channel  Units Returned  Return Rate (%)
0           b2b            6069         7.537351
1        online            5788         7.691694
2  direct sales            5625         7.399563
3  retail store            5095         6.963236
4     wholesale            4983         7.097482

In [387]:
# =====================================
# Q8: Units Returned by Return Reason
#     and Product Type
# =====================================

return_reason_product = (
    df_clean
    .pivot_table(
        values="Units Returned",
        index="Return Reason",
        columns="Product type",
        aggfunc="sum",
        fill_value=0
    )
)

return_reason_product = return_reason_product.drop(index="no return")

return_reason_product

Product type         headphones  laptops  smartphones  smartwatches  tablets
Return Reason
changed mind                867     1028         1482           600     1143
damaged in shipping         781      859          901           518      732
defective                  1974     1939         2115          1417     2143
not as described            937      917         1336          1027      833
wrong item                  610      679         1323           661      738

In [388]:
# =====================================
# Q9: Return Reasons Across Regions
# =====================================

return_reason_region = (
    df_clean[df_clean["Return Reason"] != "no return"]
    .pivot_table(
        values="Units Returned",
        index="Region",
        columns="Return Reason",
        aggfunc="sum",
        fill_value=0
    )
)

return_reason_region

Return Reason,changed mind,damaged in shipping,defective,not as described,wrong item
Region,,,,,
central,957,855,2116,910,866
east,995,737,2109,979,732
north,1027,637,1929,1200,599
south,1210,490,1791,1128,992
west,931,1072,1643,833,822

In [389]:
# Domain 3
# ===== Supplier Performance =====

In [390]:
# =====================================
# Q1: Average Supplier Quality Score
# =====================================

avg_quality_score = (
    df_clean["Quality Score"]
    .mean()
)

print(f"Average Supplier Quality Score: {avg_quality_score:.2f}")

Average Supplier Quality Score: 50.23

In [391]:
# =====================================
# Q2: Average Supplier Reliability Score
# =====================================

avg_reliability_score = (
    df_clean["Supplier Reliability Score"]
    .mean()
) * 100

print(f"Average Supplier Reliability Score: {avg_reliability_score:.2f}%")

Average Supplier Reliability Score: 65.30%

In [392]:
# =====================================
# Q3: Average Return Rate
# =====================================

avg_return_rate = (
    df_clean["Return Rate (%)"]
    .mean()
)

print(f"Average Return Rate: {avg_return_rate:.2f}%")

Average Return Rate: 7.38%

In [393]:
# =====================================
# Q4: Average Defect Rate
# =====================================

avg_defect_rate = (
    df_clean["Defect rates"]
    .mean()
)

print(f"Average Defect Rate: {avg_defect_rate:.2f}%")

Average Defect Rate: 4.98%

In [394]:
# =====================================
# Q5: Manufacturing Cost vs Quality Score
# =====================================

manufacturing_quality = (
    df_clean
    .groupby("Supplier name")
    .agg({
        "Manufacturing costs": "mean",
        "Quality Score": "mean"
    })
    .round(2)
    .sort_values(
        by="Quality Score",
        ascending=False
    )
    .reset_index()
)

manufacturing_quality

  Supplier name  Manufacturing costs  Quality Score
0    supplier 4               218.62          51.64
1    supplier 1               213.55          51.29
2    supplier 3               231.40          50.77
3    supplier 2               235.55          49.47
4    supplier 5               210.14          48.09

In [395]:
# =====================================
# Q6: Supplier Profit & Quality Score
# =====================================

supplier_profit_quality = (
    df_clean
    .groupby("Supplier name")
    .agg({
        "Profit": "sum",
        "Quality Score": "mean"
    })
    .round(2)
    .sort_values(
        by="Profit",
        ascending=False
    )
    .reset_index()
)

supplier_profit_quality

  Supplier name       Profit  Quality Score
0    supplier 2  18532887.30          49.47
1    supplier 5  17628774.89          48.09
2    supplier 3  16744544.24          50.77
3    supplier 1  16676678.49          51.29
4    supplier 4  16043915.75          51.64

In [396]:
# =====================================
# Q7: Supplier Value Score
# =====================================

supplier_value_score = (
    df_clean.groupby("Supplier name")
    .agg({
        "Quality Score":"mean",
        "Supplier Reliability Score":"mean",
        "Defect rates":"mean"
    })
)

supplier_value_score["Value Score"] = (
    supplier_value_score["Quality Score"] *
    supplier_value_score["Supplier Reliability Score"] /
    supplier_value_score["Defect rates"]
)

supplier_value_score = (
    supplier_value_score[["Value Score"]]
    .round(3)
    .sort_values(by="Value Score", ascending=False)
    .reset_index()
)

supplier_value_score

  Supplier name  Value Score
0    supplier 4        7.038
1    supplier 1        6.907
2    supplier 3        6.796
3    supplier 2        6.408
4    supplier 5        5.902

In [397]:
# =====================================
# Q8: Average Defect Rate by Supplier
# =====================================

supplier_defect_rate = (
    df_clean.groupby("Supplier name")["Defect rates"]
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

supplier_defect_rate

  Supplier name  Defect rates
0    supplier 5      5.191415
1    supplier 2      5.053061
2    supplier 3      4.923016
3    supplier 1      4.871490
4    supplier 4      4.835651

In [398]:
# =====================================
# Q9: Average Return Rate by Supplier
# =====================================

supplier_return_rate = (
    df_clean.groupby("Supplier name")["Return Rate (%)"]
    .mean()
    .round(2)
    .sort_values(ascending=False)
    .reset_index()
)

supplier_return_rate

  Supplier name  Return Rate (%)
0    supplier 5             7.72
1    supplier 1             7.45
2    supplier 4             7.33
3    supplier 3             7.22
4    supplier 2             7.18

In [399]:
# Domain 4
# ===== Inventory =====

In [400]:
# =====================================
# Q1: Total Production Volume
# =====================================

total_production = df_clean["Production volumes"].sum()

print(f"Total Production Volume: {total_production:,.0f}")

Total Production Volume: 894,440

In [401]:
# =====================================
# Q2: Total Units Sold
# =====================================

total_units_sold = df_clean["Number of products sold"].sum()

print(f"Total Units Sold: {total_units_sold:,.0f}")

Total Units Sold: 375,165

In [402]:
# =====================================
# Q3: Total Stock Available
# =====================================

total_stock = df_clean["Stock levels"].sum()

print(f"Total Stock Available: {total_stock:,.0f}")

Total Stock Available: 230,911

In [403]:
# =====================================
# Q4: Inventory Gap
# =====================================

inventory_gap = (
    df_clean["Production volumes"].sum()
    - (
        df_clean["Number of products sold"].sum()
        + df_clean["Stock levels"].sum()
    )
)

print(f"Inventory Gap: {inventory_gap:,.0f}")

Inventory Gap: 288,364

In [404]:
# =====================================
# Q5: Number of Products
# =====================================

total_products = df_clean["SKU"].nunique()

print(f"Total Products: {total_products:,}")

Total Products: 1,500

In [405]:
# =====================================
# Q6: SKU Distribution by Stockout Risk
# =====================================

df_clean["Stockout Flag"] = (
    df_clean["Stockout Risk"]
    .map({"Yes": "Risk", "No": "No Risk"})
)

stockout_distribution = (
    df_clean.groupby("Stockout Flag")["SKU"]
    .count()
    .reset_index(name="SKUs")
)

stockout_distribution["Percentage (%)"] = (
    stockout_distribution["SKUs"] /
    stockout_distribution["SKUs"].sum() * 100
).round(1)

stockout_distribution

  Stockout Flag  SKUs  Percentage (%)
0       No Risk   669            44.6
1          Risk   831            55.4

In [406]:
# =====================================
# Q7: Production Volume by Product Type
# =====================================

production_by_product = (
    df_clean.groupby("Product type")["Production volumes"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

production_by_product

   Product type  Production volumes
0   smartphones              222911
1       laptops              187316
2       tablets              181021
3    headphones              173062
4  smartwatches              130130

In [407]:
# =====================================
# Q7: Production Volume by Product Type
# =====================================

production_by_product = (
    df_clean.groupby("Product type")["Production volumes"]
    .sum()
    .reset_index()
)

production_by_product["Percentage (%)"] = (
    production_by_product["Production volumes"] /
    production_by_product["Production volumes"].sum() * 100
).round(2)

production_by_product = (
    production_by_product[["Product type", "Percentage (%)"]]
    .sort_values(by="Percentage (%)", ascending=False)
    .reset_index(drop=True)
)

production_by_product

   Product type  Percentage (%)
0   smartphones           24.92
1       laptops           20.94
2       tablets           20.24
3    headphones           19.35
4  smartwatches           14.55

In [408]:
# =====================================
# Q8: Inventory Gap & Stock Level by Product Type
# =====================================

inventory_analysis = (
    df_clean.groupby("Product type")
    .agg({
        "Production volumes":"sum",
        "Number of products sold":"sum",
        "Stock levels":"sum"
    })
)

inventory_analysis["Inventory Gap"] = (
    inventory_analysis["Production volumes"] -
    inventory_analysis["Number of products sold"] -
    inventory_analysis["Stock levels"]
)

inventory_analysis = (
    inventory_analysis[["Inventory Gap","Stock levels"]]
    .sort_values(by="Inventory Gap", ascending=False)
    .reset_index()
)

inventory_analysis

   Product type  Inventory Gap  Stock levels
0   smartphones          72829         55776
1       laptops          62450         50292
2    headphones          59786         42885
3       tablets          57264         46541
4  smartwatches          36035         35417

In [409]:
# =====================================
# Q9: Profit Margin & Units Sold by Product Type
# =====================================

product_profit = (
    df_clean.groupby("Product type")
    .agg({
        "Number of products sold":"sum",
        "Revenue generated":"sum",
        "Profit":"sum"
    })
)

product_profit["Profit Margin (%)"] = (
    product_profit["Profit"] /
    product_profit["Revenue generated"] * 100
)

product_profit = (
    product_profit[["Number of products sold","Profit Margin (%)"]]
    .round(2)
    .sort_values(by="Number of products sold", ascending=False)
    .reset_index()
)

product_profit

   Product type  Number of products sold  Profit Margin (%)
0   smartphones                    94306              47.89
1       tablets                    77216              45.99
2       laptops                    74574              46.59
3    headphones                    70391              46.67
4  smartwatches                    58678              47.34

In [410]:
# =====================================
# Q10: Top & Bottom Selling SKUs
# =====================================

top_skus = (
    df_clean[["SKU", "Number of products sold"]]
    .sort_values(by="Number of products sold", ascending=False)
    .head(5)
)

bottom_skus = (
    df_clean[["SKU", "Number of products sold"]]
    .sort_values(by="Number of products sold")
    .head(5)
)

top_bottom_skus = (
    pd.concat([top_skus, bottom_skus])
    .reset_index(drop=True)
)

top_bottom_skus

       SKU  Number of products sold
0  SKU0219                      498
1  SKU0626                      497
2  SKU0868                      497
3  SKU1454                      496
4  SKU0111                      496
5  SKU1057                       10
6  SKU0765                       10
7  SKU0547                       10
8  SKU1239                       10
9  SKU0862                       10

In [411]:
# =====================================
# Q11: Profit Margin by Price Range
# =====================================

df_clean["Price Range"] = pd.cut(
    df_clean["Price"],
    bins=[0, 400, 800, 1200, float("inf")],
    labels=["0-400", "400-800", "800-1200", "1200+"]
)

price_margin = (
    df_clean.groupby("Price Range")
    .agg({
        "Revenue generated":"sum",
        "Profit":"sum"
    })
)

price_margin["Profit Margin (%)"] = (
    price_margin["Profit"] /
    price_margin["Revenue generated"] * 100
)

price_margin = (
    price_margin[["Profit Margin (%)"]]
    .round(2)
    .reset_index()
)

price_margin

  Price Range  Profit Margin (%)
0       0-400              47.79
1     400-800              46.30
2    800-1200              48.16
3       1200+              45.42

In [412]:
# =====================================
# Q12: Defect Rate by Product Type
# =====================================

defect_rate_product = (
    df_clean.groupby("Product type")["Defect rates"]
    .mean()
    .round(2)
    .sort_values(ascending=False)
    .reset_index()
)

defect_rate_product

   Product type  Defect rates
0  smartwatches          5.42
1       tablets          5.12
2    headphones          4.94
3   smartphones          4.82
4       laptops          4.73

In [413]:
# Domain 5
# ===== Shipping & Delivery =====

In [414]:
# =====================================
# Q1: Total Shipping Cost
# =====================================

total_shipping_cost = df_clean["Shipping costs"].sum()

print(f"Total Shipping Cost: ${total_shipping_cost:,.2f}")

Total Shipping Cost: $264,672.68

In [415]:
# =====================================
# Q2: Average Lead Time
# =====================================

avg_lead_time = df_clean["Lead time"].mean()

print(f"Average Lead Time: {avg_lead_time:.2f} Days")

Average Lead Time: 13.49 Days

In [416]:
# =====================================
# Q3: Average Shipping Time
# =====================================

avg_shipping_time = df_clean["Shipping times"].mean()

print(f"Average Shipping Time: {avg_shipping_time:.2f} Days")

Average Shipping Time: 6.93 Days

In [417]:
# =====================================
# Q4: Average Shipping Cost per Shipment
# =====================================

avg_shipping_cost = df_clean["Shipping costs"].mean()

print(f"Average Shipping Cost: ${avg_shipping_cost:.2f}")

Average Shipping Cost: $176.45

In [418]:
# =====================================
# Q5: Shipping Cost & Units Shipped by Region
# =====================================

region_shipping = (
    df_clean.groupby("Region")
    .agg({
        "Number of products sold":"sum",
        "Shipping costs":"sum"
    })
    .rename(columns={
        "Number of products sold":"Units Sold",
        "Shipping costs":"Shipping Cost"
    })
    .round(2)
    .sort_values(by="Units Sold", ascending=False)
    .reset_index()
)

region_shipping

    Region  Units Sold  Shipping Cost
0    north       78406       51123.55
1  central       76824       56404.61
2    south       76166       54965.39
3     east       72590       53905.47
4     west       71179       48273.66

In [419]:
# =====================================
# Q6: Shipping Cost & Units Sold by Product Type
# =====================================

product_shipping = (
    df_clean.groupby("Product type")
    .agg({
        "Number of products sold":"sum",
        "Shipping costs":"sum"
    })
    .rename(columns={
        "Number of products sold":"Units Sold",
        "Shipping costs":"Shipping Cost"
    })
    .round(2)
    .sort_values(by="Units Sold", ascending=False)
    .reset_index()
)

product_shipping

   Product type  Units Sold  Shipping Cost
0   smartphones       94306       65122.46
1       tablets       77216       49410.78
2       laptops       74574       54540.71
3    headphones       70391       54077.33
4  smartwatches       58678       41521.40

In [420]:
# =====================================
# Q7: Best Delivery Performance by Region
# =====================================

df_clean["Delivery Status"] = (
    df_clean["On-Time Delivery"]
    .map({"Yes":"On Time", "No":"Delayed"})
)

delivery_performance = (
    df_clean.groupby(["Region", "Delivery Status"])["SKU"]
    .count()
    .reset_index(name="Orders")
)

delivery_performance = (
    delivery_performance.pivot(
        index="Region",
        columns="Delivery Status",
        values="Orders"
    )
    .reset_index()
)

delivery_performance = delivery_performance[
    ["Region", "On Time", "Delayed"]
]

delivery_performance

Delivery Status   Region  On Time  Delayed
0                central      241       49
1                   east      230       67
2                  north      248       65
3                  south      255       57
4                   west      232       56

In [421]:
# =====================================
# Q8: On-Time vs Delayed Orders
# =====================================

delivery_status = (
    df_clean.groupby("Delivery Status")["SKU"]
    .count()
    .reset_index(name="Orders")
)

delivery_status["Percentage (%)"] = (
    delivery_status["Orders"] /
    delivery_status["Orders"].sum() * 100
).round(1)

delivery_status

  Delivery Status  Orders  Percentage (%)
0         Delayed     294            19.6
1         On Time    1206            80.4

In [422]:
# =====================================
# Q9: Average Shipping Duration by Region
# =====================================

shipping_duration = (
    df_clean.groupby("Region")["Shipping times"]
    .mean()
    .round(2)
    .reset_index(name="Average Shipping Duration")
    .sort_values(by="Average Shipping Duration")
)

shipping_duration

    Region  Average Shipping Duration
4     west                       6.66
0  central                       6.80
2    north                       6.90
3    south                       6.96
1     east                       7.31

In [424]:
# =====================================
# Q10: Profit by Delivery Status
# =====================================

profit_delivery = (
    df_clean.groupby("Delivery Status")["Profit"]
    .sum()
    .round(2)
    .reset_index()
    .sort_values(by="Profit", ascending=False)
)

profit_delivery

  Delivery Status       Profit
1         On Time  71298327.39
0         Delayed  14328473.28